# Generated by Django 5.2.1 on 2025-05-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20250513_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mode',
            field=models.CharField(choices=[('single', 'Single Player'), ('multi', 'Multiplayer'), ('story', 'Story Mode')], default='single', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('rpg', 'RPG'), ('strategy', 'Strategy'), ('simulation', 'Simulation'), ('puzzle', 'Puzzle')], max_length=20),
        ),
    ]
