# Generated by Django 5.2.1 on 2025-05-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_mode_alter_game_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='title',
        ),
    ]
